<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2015.0.2.310
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Tickets Form Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'msirikasem@hotmail.com',
		'to' => 'msirikasem@hotmail.com'
	),
	'fields' => array(
		'custom_U1014' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Name',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Name\' is required.'
			)
		),
		'Email' => array(
			'order' => 4,
			'type' => 'email',
			'label' => 'Email',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Email\' is required.',
				'format' => 'Field \'Email\' has an invalid email.'
			)
		),
		'custom_U1010' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Name (appear on card)',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Name (appear on card)\' is required.'
			)
		),
		'custom_U1001' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'Credit Card',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Credit Card\' is required.'
			)
		),
		'custom_U992' => array(
			'order' => 8,
			'type' => 'string',
			'label' => 'Expiration Date',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Expiration Date\' is required.'
			)
		),
		'custom_U996' => array(
			'order' => 9,
			'type' => 'string',
			'label' => 'Address 1',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Address 1\' is required.'
			)
		),
		'custom_U1026' => array(
			'order' => 10,
			'type' => 'string',
			'label' => 'Address 2',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Address 2\' is required.'
			)
		),
		'custom_U1090' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'Custom',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Custom\' is required.'
			)
		),
		'custom_U1095' => array(
			'order' => 11,
			'type' => 'string',
			'label' => 'City',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'City\' is required.'
			)
		),
		'custom_U1103' => array(
			'order' => 12,
			'type' => 'string',
			'label' => 'Country',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Country\' is required.'
			)
		),
		'custom_U1107' => array(
			'order' => 13,
			'type' => 'string',
			'label' => 'State/Province',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'State/Province\' is required.'
			)
		),
		'custom_U1111' => array(
			'order' => 14,
			'type' => 'string',
			'label' => 'Custom',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Custom\' is required.'
			)
		),
		'custom_U1115' => array(
			'order' => 15,
			'type' => 'string',
			'label' => 'Phone',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Phone\' is required.'
			)
		),
		'custom_U1125' => array(
			'order' => 1,
			'type' => 'checkbox',
			'label' => 'Limited Edition Tickets',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Limited Edition Tickets\' is required.'
			)
		),
		'custom_U1161' => array(
			'order' => 2,
			'type' => 'checkbox',
			'label' => 'Regular Tickets',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Regular Tickets\' is required.'
			)
		)
	)
);

process_form($form);
?>
